### ISSUE TITLE
Using Kibana Prometheus Exporter with Elastic Operator

### ISSUE THREAD

**Issue by FelixRodriguezJara** [pjhampton/kibana-prometheus-exporter#137]
Hi!

First of all, thank you very much for generating a Prometheus Metrics exporter for Kibana, it is really interesting. We have deployed Elasticsearch and Kibana using the Kubernetes Elasticsearch Operator, so, I don´t quite directly control the Kibana deployment definition. I am trying to find out a way of adding the plugin so I can get metrics exported from my Kibana instance. Is the plugin something that needs to run together with the Kibana container within the same pod or it can be deployed independently? Do you have any Dockerfile I could use as a reference?

Any feedback on deploying the plugin in kubernetes is very much appreciated.

Thank you very much.

Kind regards.

**Comment by pjhampton** [comment]
Hey @FelixRodriguezJara 

Thanks so much for the kind words and your question! I really appreciate it.

I haven't used Kubernetes Elasticsearch Operator before so I had to read into it. 
Here is an example Dockerfile you could use: https://github.com/x0rzkov/dockerfiles-search/blob/f1a7d092b9c31024507459bf677136d907758a5f/hub.docker.com/mikelorant/kibana/Dockerfile 

What you want to do is use the official image as your base image and just install the plugin on top of that. It looks like you can do this: https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-bundles-plugins.html but you would have to host the image in docker hub or some sort of internal artifact hosting service like artifactory.

Or it looks like you can alter your kubernetes deployment and just install the plugin on start up (got that from that link).

```
spec:
  nodeSets:
  - name: default
    count: 3
    podTemplate:
      spec:
        initContainers:
        - name: install-plugins
          command:
          - sh
          - -c
          - |
            bin/kibana-plugin install https://github.com/pjhampton/kibana-prometheus-exporter/releases/download/7.6.0/kibana-prometheus-exporter-7.6.0.zip
```

Alternatively, you could skip using the plugin if you don't care for the metrics and just want to know if it's up or down - _what most people care about_. In that case you should use the official blackbox exporter - https://github.com/prometheus/blackbox_exporter

Let me know what you end up doing and I can improve the README :-)
