### ISSUE TITLE
Support basic auth in plugin

### ISSUE THREAD

**Issue by rajeshwer** [pjhampton/kibana-prometheus-exporter#31]
Basic auth is enabled in my kibana/elasticsearch 
how do i pass the user/pass while using this plugin??

{
statusCode: 500,
error: "Internal Server Error",
message: "An internal server error occurred"
}

version: 6.3.2

**Comment by pjhampton** [comment]
Hey @rajeshwer 

How have you set up basic auth? Behind nginx or something?

**Comment by rajeshwer** [comment]
yes

**Comment by pjhampton** [comment]
Just to let you know, this feature has been added, it just needs to be merged back in time and rereleased.

**Comment by JPLachance** [comment]
Hello!

I just installed this plugin in Kibana 6.3.2. Our Elasticsearch server is using X-Pack and each time I try to access the `/_prometheus/metrics` endpoint, I get an error 500.

From the Kibana container, if I call the endpoint with curl:
```bash
bash-4.2$ curl -k -XGET https://127.0.0.1:5601/_prometheus/metrics -v
* About to connect() to 127.0.0.1 port 5601 (#0)
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 5601 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
* skipping SSL peer certificate verification
* SSL connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate:
* 	subject: CN=*.my.domain.com,OU=PositiveSSL Wildcard,OU=Domain Control Validated
* 	start date: Mar 25 00:00:00 2019 GMT
* 	expire date: Mar 01 23:59:59 2020 GMT
* 	common name: *.my.domain.com
* 	issuer: CN=Sectigo RSA Domain Validation Secure Server CA,O=Sectigo Limited,L=Salford,ST=Greater Manchester,C=GB
> GET /_prometheus/metrics HTTP/1.1
> User-Agent: curl/7.29.0
> Host: 127.0.0.1:5601
> Accept: */*
> 
< HTTP/1.1 302 Found
< location: /login?next=%2F_prometheus%2Fmetrics
< kbn-name: kibana
< kbn-version: 6.3.2
< kbn-xpack-sig: a02d1baedd74fa53c17b223d8968a61a
< cache-control: no-cache
< content-length: 0
< Date: Wed, 10 Apr 2019 14:22:27 GMT
< Connection: keep-alive
< 
* Connection #0 to host 127.0.0.1 left intact
```

Was your support for X-Pack basic authentication released for Kibana 6.3.2? If no, how can I help? :) I'm stuck with Kibana 6.3.2 and I cannot upgrade at the moment.

Thanks!

**Comment by pjhampton** [comment]
Thanks guys. I have added basic auth to 6.3.2

The release process is a real pain in the ass because of the way kibana enforces it . and I have been putting this off until I fix https://github.com/pjhampton/kibana-prometheus-exporter/issues/58 as I don't want to redo these releases twice.

As there is enough demand for 6.3.2 though, see:
See https://github.com/pjhampton/kibana-prometheus-exporter/releases/tag/6.3.2

**Comment by xkkker** [comment]
@pjhampton hi, I wonder how to config the plugin to get the metrics through /_prometheus/metrics if I has x-pack enabled?
Now I enabled the plugin but I can't get the metrics:
```
[sudo_ops@s15-yolanda ~]$ curl 172.16.1.28:35601/_prometheus/metrics -v
* About to connect() to 172.16.1.28 port 35601 (#0)
*   Trying 172.16.1.28...
* Connected to 172.16.1.28 (172.16.1.28) port 35601 (#0)
> GET /_prometheus/metrics HTTP/1.1
> User-Agent: curl/7.29.0
> Host: 172.16.1.28:35601
> Accept: */*
>
< HTTP/1.1 302 Found
< location: /login?next=%2F_prometheus%2Fmetrics
< kbn-name: kibana
< kbn-xpack-sig: 43ec5b777d893cc840fcb6c81a1d492b
< content-type: text/html; charset=utf-8
< cache-control: no-cache
< content-length: 0
< connection: close
< Date: Mon, 11 Nov 2019 07:30:18 GMT
<
* Closing connection 0
```

**Comment by pjhampton** [comment]
@xkkker what ver? Also, How have you deployed as that is a non standard port?

**Comment by xkkker** [comment]
@pjhampton  Thanks for your reply! The kibana's version is 7.0.1.
And I run it on my vm instead in docker. The port is 35601 because I change the default port in the kibana.yml, the following is a section in my kibana.yml:
```
# Kibana is served by a back end server. This setting specifies the port to use.
server.port: 35601

# Specifies the address to which the Kibana server will bind. IP addresses and host names are both valid values.
# The default is 'localhost', which usually means remote machines will not be able to connect.
# To allow connections from remote users, set this parameter to a non-loopback address.
server.host: "0.0.0.0"
```
And my question is ,how to expose the metrics when I has the x-pack authentication enabled?
Thank you ~

**Comment by matagyula** [comment]
Greetings,
I'm facing the same issue as the original commenter who started this thread. I have Kibana version 7.3.1 with prometheus-exporter version 7.3.1.0 - the plugin is listed correctly when I run GET _cat/plugins from the Kibana DEV tools.

I'm trying to reach the metrics endpoint using CURL from the host running Kibana:
curl -v https://x.x.x.x:5601/kibana/_prometheus/metrics -k -u xxxxx

This gets me a HTTP/1.1 500 Internal Server Error response. 

A couple things to note here: SSL is enabled, kibana is running on the /kibana endpoint, XPACK security is enabled, and the curl command asks for my password, which is OK.

Any and all help is appreciated :) thank you!

**Comment by pjhampton** [comment]
Hey @matagyula - sounds like you have things pretty locked down - which is great! 🤘 

SSL isn't an issue, as it is one-way TLS (AFAIK) exchange which is bypassed.
https://github.com/pjhampton/kibana-prometheus-exporter/blob/master/server/exporter/prometheus.js#L11 See the code here. Maybe I should document it somewhere.

It picks up the values in 

```
server.basePath: "/kibana"                                                                                                                                                                                                            
server.rewriteBasePath: true 
```

and I get the values just fine from `http://localhost:5601/kibana/_prometheus/metrics`

As for the user/pass for the basic auth, you can set a user in the config as:

```
kibana-prometheus-exporter.user: user
kibana-prometheus-exporter.pass: password
```

where user/password are your actual username/password. Hope that helps.

**Comment by pjhampton** [comment]
@xkkker does putting the below in your `config/kibana.yml` help at all?

```
kibana-prometheus-exporter.user: user
kibana-prometheus-exporter.pass: password
```

where user/password are your actual username/password for an x-pack user. Can you send me some info on how I can set up X-pack? I did it before before it was bundled with elastic and the docs are maybe lacking slightly around this topic.

**Comment by matagyula** [comment]
Hi @pjhampton ,  thank you very much for your prompt response. Setting the username and password in the kibana.yml config file helped. I can now access the metrics endpoint :) Thank you once again! Cheers!

**Comment by JPLachance** [comment]
Hello @pjhampton,

I'm trying to run my own Kibana instance on top of the AWS Elasticsearch service with [fine-graned access control enabled](https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/fgac.html). Fine-grained access control in the AWS Elasticsearch service is leveraging the [Open Distro for Elasticsearch security plugin](https://opendistro.github.io/for-elasticsearch-docs/docs/security-configuration/configuration/).

I installed the kibana-prometheus-exporter plugin, the plugin status is green, but it does not serve the `_prometheus/metrics` as expected.
```JSON
{
  "id": "plugin:kibana-prometheus-exporter@7.4.2",
  "state": "green",
  "icon": "success",
  "message": "Ready",
  "uiColor": "secondary",
  "since": "2020-04-01T16:53:46.953Z"
}
```

From my Kibana container, if I run `curl -k https://0.0.0.0:5601/api/status?extended -v`, I guess the Kibana status as expected. I used the `status.allowAnonymous: true` Kibana parameter to make the status API available without authentication.

But, when I try get prometheus metrics using `curl -k https://0.0.0.0:5601/_prometheus/metrics -v`, it gives me the 302 redirect to the login page. I also tried to pass a password `curl -k -u admin:secret https://0.0.0.0:5601/_prometheus/metrics -v`, it did not work.

Is there any way I could enable a debug mode for your plugin and explore logs? Since `curl -k https://0.0.0.0:5601/api/status?extended -v` works fine, I really don't understand why the plugin would not work.

Thanks in advance for your help!! 😄

**Comment by pjhampton** [comment]
👋@JPLachance Can you share your kibana.yml and omit any secrets / credentials.

**Comment by JPLachance** [comment]
I sure can:
```YAML
server.name: "kibana"
server.host: "0.0.0.0"
server.port: 5601
server.ssl.enabled: true
server.ssl.certificate: /usr/share/kibana/config/certs/tls.crt
server.ssl.key: /usr/share/kibana/config/certs/tls.key

elasticsearch.hosts:
  - "${es_url}"
elasticsearch.ssl.verificationMode: none
elasticsearch.username: "${es_kibana_user_username}"
elasticsearch.password: "${es_kibana_user_password}"
elasticsearch.requestHeadersWhitelist: ["securitytenant","Authorization"]
elasticsearch.requestTimeout: 500000

# Disabled for now
opendistro_security.multitenancy.enabled: false

opendistro_security.readonly_mode.roles: ["kibana_read_only"]
opendistro_security.cookie.password: "${cookie_password}"
opendistro_security.cookie.secure: true
opendistro_security.cookie.ttl: 86400000
opendistro_security.session.keepalive: false
opendistro_security.session.ttl: 86400000

# Based on the AWS documentation, we must use the ".kibana_1" index
kibana.index: ".kibana_1"
kibana.defaultAppId: "discover"

logging.dest: stdout
logging.quiet: true

# Make sure the status API is available to Kubernetes readiness probes
status.allowAnonymous: true
```

I hope it helps 🙂
